### ISSUE TITLE
waitpid failed

### ISSUE THREAD

**Issue by zfuller5280** [ThomasPak/pakman#2]
Hello,
I am running an ABC SMC using the mpi master. I have all of the programs in C++ and compiled on one cluster environment, and things are running great. However, I compiled all of the C++ programs (and pakman) on another cluster I have access to in what I thought was an identical fashion but am getting the following error occasionally:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  waitpid of ./simulator 8.105400000000001e-07 18 .5 1 0 0 1 1 11 1 110598 failed
```
Here, the `./simulator` command is my custom simulator I am using (with the numbers that follow sued as arguments). What is strange, is that this seems to happen at random. Sometimes it will run all the way through without issue, and other times, using the same inputs and command, it will produce the above error on at least one of the parallel processes. I've tried to look at the source code, but am not understanding what is causing an error with `waitpid`, can you please explain what causes this to be thrown? Sorry, I'm not the best at C++ to begin with, so this may be part of the issue. Furthermore, do you have any ideas as to why it would run correctly on one cluster, but then have these issues with another? For both, I am using `Intel(R) MPI Library for Linux* OS, Version 2019 Build 20180829`, and I believe everything else is the same, so I'm at a loss for what the source of this error could be. Thanks for any help or suggestions!

**Comment by ThomasPak** [comment]
Hi Zach,

First of all, sorry for the delayed response. I was on a holiday and then started a new job, so it has been quite hectic.

According to the documentation (`man waitpid`), there are three different ways that `waitpid` can fail:

- EINVAL: `waitpid` was called with an invalid `options` argument. In the source code, `waitpid` is only called with valid arguments, so this possibility can be eliminated.
- ECHILD: `waitpid` was called with an invalid child pid.
- EINTR: `waitpid` was interrupted by a signal.

Unfortunately, the error message does not distinguish between these different errors, so we can't know which specific error is causing your simulation to fail. Therefore, I have added some code in the last two commits that will report which error occurred in the error message.

Could you please pull the latest version of the pakman repository, and then re-run your simulations? When it fails because of `waitpid`, it should now print out the specific `waitpid` error.

**Comment by zfuller5280** [comment]
Thanks for the reply! I pulled the latest version and it now gives the specific `waitpid` error as you mention. The error I am getting is `errno = ECHILD`. I see this is caused by an invalid child pid, do you happen to have any more detail or information on what could be the cause of this? I'm still not sure why this would run fine on one cluster but throw an error on another, do you think it could be related to an error with the version of MPI I am using? Thanks again for any information, and no worries if you can't provide any further information for my specific error.

**Comment by ThomasPak** [comment]
I suspect this is an issue related to your MPI library. Not all MPI libraries support calling `fork()` in MPI processes, and when they do, they may support it imperfectly. I don't know how to help you any further with this, so I am closing the issue for now.
